_target_: src.models.classifier.ClassifierLightningModule

num_classes: 1000

clf:
  _target_: src.nets.timm.Timm

  model_name: resnet18
  pretrained: True
  num_classes: 1000

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True

  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true

  eta_min: 1e-6
