_target_: src.models.diffusion_image_enhancement.ImageEnhancementLightningModule

defaults:
  - unet: big
  - diffusion: isb

vae:
  _target_: src.nets.vae.VAE
  model_id: "stabilityai/stable-diffusion-x4-upscaler"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True

  lr: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: True

  eta_min: 1e-6
