run:
  dir: ${paths.log_dir}/runs/${slurm_prefix:}${name}_${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ${paths.log_dir}/multiruns/${multirun_name}/${slurm_prefix:}${name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}-${name}
