model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint

  dirpath: "${paths.output_dir}/checkpoints"
  filename: "epoch={epoch:02d}-step={step:02d}-val_acc={val/acc:.4f}"
  save_last: True
  save_top_k: 1
  monitor: "val/acc"
  mode: "max"
  auto_insert_metric_name: False
