defaults:
  - _self_

  - core: default

  - data: cifar10
  - model: classifier

  - trainer: default
  - callbacks: default
  - wandb: default
  - hydra: default

  - experiment: null

train: True
test: False

ckpt_path: null
