defaults:
  - default.yaml

  - override data: cifar10-diffusion
  - override model: diffusion

name: diffusion

trainer:
  limit_val_batches: 1
  limit_test_batches: 1

callbacks:
  model_checkpoint:
    monitor: null
